### PR TITLE
Convert libkhax to submodule

### PR DESCRIPTION
**Pull request by cloudburst**
This is required to build on libctru-1.0.0 and also pulls in newer libkhax updates.

### CODE REVIEW

**Comment by d0k3** [comment]
Is this and the other pull request properly tested? Can't test for a while, but I already know these changes, so I guess I'll just trust you if you say so. Also, you should have put both commits into one pull request!

**Comment by cloudburst** [comment]
Both just fix the compilation errors since the current source won't build.

I have not done a bunch of boot tests or anything yet but both pulls should have already been tested within the Brahma2Loader branch.

I figured it would be easier for you to evaluate them separately by splitting them into two pull requests :p

**Comment by d0k3** [comment]
Alright, but the BrahmaLoader for MiniPasta is not the same as the one in my fork. You tried it at least once, right?

**Comment by cloudburst** [comment]
Yeah I booted it once on my 9.2 o3DS and it works fine for me.  That is the extent of my "testing" though, so feel free to delay pulling until you can test it more.

With the two pull requests, the only other change needed to compile and boot is to convert arm9payload.bin into an arm9payload_bin.h so main.c can find it.  zoogie left this out of the original source

**Comment by d0k3** [comment]
The arm9payload_bin.h is automagically created from arm9payload.bin. The .bat files handle this. If that does not work for you, somethings going wrong.

**Comment by cloudburst** [comment]
Oh, I'm running it on linux.  I see the build.bat now:

```
md data
cp arm9payload/arm9payload.bin data
```

I just did those two steps manually

```
mkdir data
cp arm9payload/arm9payload.bin data
```

and the Makefile generates the arm9payload_bin.h now, thanks.

**Comment by d0k3** [comment]
Merged both. Well, if you want to, you can create build.sh / clean.sh for Linux. Or (better) let the Makefile handle everything. To be honest, I don't intend to develop this further, I'm just maintaining the code here so it doesn't get lost. Thanks for that pull request!
